// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/exams": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new exam for class/subject.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "Create exam",
                "parameters": [
                    {
                        "description": "Exam payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateExamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/marks": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Enter or update marks for a student in an exam.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "Enter marks",
                "parameters": [
                    {
                        "description": "Marks payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EnterMarksRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Mark"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/results": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch computed result entries for report cards.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Results"
                ],
                "summary": "Get results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Exam ID",
                        "name": "exam_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Student ID",
                        "name": "student_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Class ID",
                        "name": "class_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ResultItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/results/publish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Publish exam results for report card visibility.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Results"
                ],
                "summary": "Publish results",
                "parameters": [
                    {
                        "description": "Publish payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PublishResultRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CreateExamRequest": {
            "type": "object",
            "required": [
                "class_id",
                "exam_date",
                "title",
                "total_marks"
            ],
            "properties": {
                "class_id": {
                    "type": "string"
                },
                "exam_date": {
                    "type": "string"
                },
                "section_id": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_marks": {
                    "type": "number"
                }
            }
        },
        "model.EnterMarksRequest": {
            "type": "object",
            "required": [
                "exam_id",
                "marks_obtained",
                "student_id"
            ],
            "properties": {
                "exam_id": {
                    "type": "string"
                },
                "marks_obtained": {
                    "type": "number"
                },
                "remarks": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "something went wrong"
                }
            }
        },
        "model.Exam": {
            "type": "object",
            "properties": {
                "class_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "exam_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_published": {
                    "type": "boolean"
                },
                "school_id": {
                    "type": "string"
                },
                "section_id": {
                    "type": "string"
                },
                "subject_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_marks": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.Mark": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "exam_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "marks_obtained": {
                    "type": "number"
                },
                "remarks": {
                    "type": "string"
                },
                "school_id": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.PublishResultRequest": {
            "type": "object",
            "required": [
                "exam_id"
            ],
            "properties": {
                "exam_id": {
                    "type": "string"
                }
            }
        },
        "model.ResultItem": {
            "type": "object",
            "properties": {
                "exam_date": {
                    "type": "string"
                },
                "exam_id": {
                    "type": "string"
                },
                "exam_title": {
                    "type": "string"
                },
                "grade": {
                    "type": "string"
                },
                "marks_obtained": {
                    "type": "number"
                },
                "percentage": {
                    "type": "number"
                },
                "published": {
                    "type": "boolean"
                },
                "student_id": {
                    "type": "string"
                },
                "total_marks": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8086",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Exam Service API",
	Description:      "Exam lifecycle service for exams, marks and results.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
